### ISSUE TITLE
Sent Firo to Campfire wallet and it shows as pending even after multiple confirmations

### ISSUE THREAD

**Issue by nrsimha** [cypherstack/Campfire#1]
I have Campfire 1.2.3 and send Firo to it.

In Firo explorer it shows already more than 15 confirmations, but app shows transaction as pending.
In network page it shows Blockchain status as synchronised.

Tried pressing top left icon to synchronise, but it still shows as pending.

After hour of sending I tried to import recovery passphrase into Firo Electrum wallet and there it shows as received.

If you need more info or look in some kind of debugging you can contact me also on Telegram (nrsimha).

**Comment by KuroGuo** [comment]
Same to me

<img src="https://user-images.githubusercontent.com/8684548/156234895-9d4af094-8276-4d27-810c-00943a4b9735.jpg" alt="7f0e0d30a85329118a09861853ae98a" width="300">

**Comment by msalazarm** [comment]
Thanks, It should be addressed now in https://github.com/cypherstack/Campfire/commit/269d1e500b67aaa4014430fd284ba7b68bda2b3e
update is now pushed to play store.

**Comment by nrsimha** [comment]
I updated through Play store to 1.2.4 and transaction is still pending.

**Comment by KuroGuo** [comment]
I tried 1.2.5 and it seems the issue is fixed.

**Comment by nrsimha** [comment]
Version 1.2.5 appeared to me right now and it fixes the issue.
